version: '3.8'

services:
  test-db:
    image: postgres:16-alpine
    container_name: cleansweep-test-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cleansweep_test
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: cleansweep-test-runner
    depends_on:
      test-db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@test-db:5432/cleansweep_test
      NEXT_PUBLIC_SUPABASE_URL: http://localhost:9002
      NEXT_PUBLIC_SUPABASE_ANON_KEY: test-key-for-testing
      NODE_ENV: test
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./jest.config.js:/app/jest.config.js
      - ./jest.setup.js:/app/jest.setup.js
    command: >
      sh -c "
        echo '🚀 Starting test runner...' &&
        echo '📋 Running smoke tests...' &&
        npm test -- src/__tests__/smoke.test.ts --verbose
      "